first_names = {
    "bandit": [
        "Zhorka",
        "Timoha",
        "Vasyan",
        "Vetal",
        "Mihas",
        "Mihal",
        "Sanyok",
        "Felka",
        "Grishka",
        "Miha",
        "Styopka",
        "Grishko",
        "Arkasha",
        "Ilyuha",
        "Shurik",
        "Tyomka",
        "Vovan",
        "Yashka",
        "Andryuha",
        "Vasek",
        "Fimka",
        "Petruha",
        "Boryan",
        "Vadya",
        "Tolay",
        "Toha",
        "Bodya",
        "Lyoha",
        "Vityuha",
        "Zheka",
        "Kolyan",
        "Kostyan",
        "Dimon",
        "Mitka",
        "Pavluha",
        "Dimuha",
        "Yuras",
        "Stepuha",
    ],
    "stalker": [
        "Gosha",
        "Yara",
        "Anton",
        "Sava",
        "Edik",
        "Germain",
        "Vanya",
        "Borya",
        "Romka",
        "Danko",
        "Shurik",
        "Filya",
        "Gena",
        "Stepan",
        "Lyova",
        "Danya",
        "Senya",
        "Vadya",
        "Vitya",
        "Kostik",
        "Fyodor",
        "Slavik",
        "Nikita",
        "Vadim",
        "Kostya",
        "Valera",
        "Sevka",
        "Zhenya",
        "Toshka",
        "Vasya",
        "Petya",
        "Vaska",
        "Kolya",
        "George",
        "Misha",
        "Vovka",
        "Ilya",
        "Vitka",
        "Petka",
        "Rus",
        "Filka",
        "Matvey",
        "Yury",
        "Dmitro",
        "Vitalik",
        "Grisha",
        "Yasha",
        "Sanyok",
        "Lenka",
        "Grishko",
        "Alex",
        "Syoma",
        "Tolik",
        "Petro",
        "Yarik",
        "Bogdan",
        "Zhenka",
        "Seryoga",
        "Arthur",
        "Seva",
        "Fedya",
        "Max",
        "Dima",
        "Lyonya",
        "Pashka",
        "Denis",
        "Mitya",
        "Pasha",
        "Artyom",
        "Lyoshka",
        "Vlad",
        "Sanya",
        "Gleb",
        "Tima",
        "Dimka",
        "Stepa",
        "Roma",
        "Fedka",
        "Valik",
        "Semyon",
        "Oleg",
        "Genka",
        "Grishka",
        "Slava",
        "Nik",
        "Vanka",
        "Rostik",
        "Yashka",
        "Danila",
        "Egor",
        "Igoryok",
        "Fima",
        "Venya",
        "Yurka",
        "Zhora",
        "Vadik",
        "Yurko",
        "Egorka",
        "Vova",
        "Mishka",
        "Vasko",
        "Timka",
        "Borka",
    ],
}

last_names = {
    "bandit": [
        "La Loque",
        "Boulon",
        "Kaschey",
        "Commandant",
        "L'Atout",
        "La Banane",
        "Le Poing",
        "Susanin",
        "Crado",
        "Fripouille",
        "Le Furieux",
        "La Crapule",
        "L'Accordéon",
        "L'Appliqué",
        "L'Avocat",
        "Le Parrain",
        "Ninja",
        "Cochon",
        "Burin",
        "Le Poing ",
        "Le Poivré",
        "Le Boucher",
        "Le Borgne",
        "Le Gentil",
        "Le Pirate",
        "L'Infirme",
        "Troglodyte",
        "Bud",
        "Le Dingue",
        "Le Baron",
        "La Perceuse",
        "Le Suspect",
        "Chirurgien",
        "Le Partisan",
        "Le Vieux",
        "Le Cravateur",
        "Bouledogue",
        "L'Exclu",
        "L'Andouille",
        "La Râpe",
        "Le Convoyeur",
        "Le Serpent",
        "Le Brigand",
        "Tiranas",
        "La Tige",
        "Le Grison",
        "Le Natif",
        "Néant",
        "La Chique",
        "Le Punk",
        "Le Mutileur",
        "Le Pyromane",
        "Leary",
        "Le Grincheux",
        "Le Pic",
        "Le Bourreau",
        "Barmaley",
        "Le Despote",
        "Le Clochard",
        "Jack",
        "L'Extermin.",
        "Le Crochet",
        "Tête brûlée",
        "La Tache",
        "La Flore",
        "Pied-de-biche",
        "Le Rocher",
        "Le Poinçon",
        "Le Fou",
        "Patsyuk",
        "Le Pingre",
        "L'Estropieur",
        "La Rancune",
        "Le Chacal",
        "L'Aveugle",
        "L'As",
        "L'Élan",
        "Le Bavard",
        "Le Rasoir",
        "La Tuile",
        "Panadol",
        "La Saucisse",
        "Pacifique",
        "Le Tanné",
        "Tas de viande",
        "Dolittle",
        "Le Messager",
        "L'Étrangleur",
        "La Matraque",
        "Le Graphe",
        "Fossoyeur",
        "Le Mac",
        "Le Comique",
        "La Raclette",
        "Le Moineau",
        "Le Dealer",
        "Le Décadent",
        "Dynamite",
        "L'Embrouille",
        "Le Boa",
        "La Punaise",
        "Le Monstre",
        "Le Joueur",
        "L'Écorné",
        "Le Voleur",
        "Le Bossu",
        "Zmur",
        "La Bête",
        "Le Glacé",
        "Le Louchard",
        "Le Ridé",
        "La Gangrène",
        "Batiy",
        "La Dépouille",
        "Le Balafré",
        "Le Taureau",
        "Le Pétard",
        "Le Légiste",
        "La Boussole",
        "Le Bourge",
        "Le Castor",
        "Piston",
        "Le Chimiste",
        "L'Invétéré",
        "Bourbon",
        "Le Percé",
        "Le Banquier",
        "Le Morveux",
        "Le Putride",
        "Le Tambourin",
        "Le Maure",
        "Le Peureux",
        "Trésor",
        "Flamen",
        "Le Buffle",
        "Le Bosco",
        "Le Ver",
        "Charlatan",
        "Leshiy",
        "Le Joker",
        "Le Hippie",
        "Le Vagabond",
        "Le Bloc",
        "La Goule",
        "La Croix",
        "Le Canari",
        "Le Sanglier",
        "Pile",
        "Crâne d'oeuf",
        "L'Esthète",
        "Le Cintré",
        "La Plume",
        "La Carpe",
        "Spliff",
        "L'Arrache",
        "Le Sauvage",
        "Le Diplômé",
        "L'Artiste",
        "Chapay",
        "Nickel",
        "La Mort",
        "Clodo",
        "L'imberbe",
        "Le Mutilé",
        "Le Balèze",
        "La Quenelle",
        "La Mèche",
        "L'Outarde",
        "Maniaque",
        "Le Prince",
        "Le Tueur",
        "Le Rémouleur",
        "Le Parasite",
        "L'Espion",
        "Teddy",
        "Genghis",
    ],
    "stalker": [
        "La Loi",
        "Le Mégot",
        "L'Enseignant",
        "Commandant",
        "La Banane",
        "Susanin",
        "Crado",
        "Le Furieux",
        "Cognac",
        "Le Gardien",
        "L'Appliqué",
        "L'Avocat",
        "Le Python",
        "Le Farceur",
        "Voland",
        "L'Apôtre",
        "L'Anaconda",
        "Le pèlerin",
        "Le Bouteur",
        "Le Piégeur",
        "Le Mouchard",
        "L'Érudit",
        "Cardan",
        "César",
        "Le Gentil",
        "Le Maître",
        "Le Guerrier",
        "Troglodyte",
        "Dexter",
        "Le Fouet",
        "La Perceuse",
        "Chirurgien",
        "Le Muet",
        "Le Vieux",
        "Le Cravateur",
        "L'Exclu",
        "L'Andouille",
        "L'Os",
        "L'Armoire",
        "Le Patron",
        "L'Araignée",
        "Simulateur",
        "La Bulle",
        "La Chance",
        "Le Brave",
        "Le Joint",
        "Le Tampon",
        "L'Aurochs",
        "Colonel",
        "Le Squelette",
        "Le Clochard",
        "Le Sauveteur",
        "La Gerboise",
        "Le Crochet",
        "La Flore",
        "La Tache",
        "Homère",
        "Le Fantôme",
        "Le Papy",
        "Le Pingre",
        "Le Souffleur",
        "L'As",
        "La Tuile",
        "Le Bûcheron",
        "Benny",
        "La Matraque",
        "La Griffe",
        "La Crevette",
        "Fossoyeur",
        "Le Gladiateur",
        "Le Mac",
        "Télégraphe",
        "Le Hérisson",
        "Le Moineau",
        "Le Mécène",
        "La Punaise",
        "L'Asticot",
        "Narcisse",
        "L'Obus",
        "Révérend",
        "L'Écorné",
        "Le Martien",
        "La Bête",
        "La Pipelette",
        "La Spatule",
        "Le Chanceux",
        "Le Forestier",
        "Le Postier",
        "L'Étranger",
        "Le Robot",
        "Le Beignet",
        "Le Blanc",
        "Le Rabbin",
        "Piston",
        "Le Mineur",
        "Le Percé",
        "Carbure",
        "Le Païen",
        "Le Faucheur",
        "Le Bûcheur",
        "Le Voyageur",
        "Le Peureux",
        "Trésor",
        "Le Buffle",
        "Le Pivot",
        "Le Loyal",
        "Barabashka",
        "Ambassadeur",
        "Genghis",
        "L'Alligator",
        "Le Légion.",
        "Le Bloc",
        "L'Ancien",
        "La Goule",
        "La Chouette",
        "La Botte",
        "Le Mort",
        "Le Cow-boy",
        "Le Sanglier",
        "Le Gros",
        "L'Explorateur",
        "La Triche",
        "Le Viking",
        "Le Corbeau",
        "L'Invincible",
        "Choucroute",
        "Le Rat musqué",
        "Chapay",
        "Le Lanceur",
        "Le Maladroit",
        "Frisquet",
        "Le Ventilateur",
        "Le Sorcier",
        "Le Balèze",
        "Pleurnicheur",
        "Le Calibre",
        "Le Creuseur",
        "L'Heureux",
        "L'Ensorceleur",
        "Le Gringalet",
        "La Lanterne",
        "Le Fer",
        "Le Nettoyeur",
        "Doc",
        "Transporteur",
        "Le Rouquin",
        "L'Anomalie",
        "Le Glaçon",
        "Padishah",
        "La Passoire",
        "Siniy",
        "Le Lapin",
        "L'Ours",
        "Le Chaman",
        "La Joconde",
        "Burin",
        "Le Bouffon",
        "Casanova",
        "Le Pointeur",
        "La Gousse",
        "Pinocchio",
        "Le Dingue",
        "Python",
        "Le Baron",
        "Le Mutant",
        "Le Partisan",
        "Le Roc",
        "Bouledogue",
        "Le Brigand",
        "La Tige",
        "L'Opérateur",
        "Le Charpentier",
        "Bibine",
        "L'invité",
        "Le Punk",
        "Le Pyromane",
        "Le Peintre",
        "L'Aspirateur",
        "Le Duc",
        "Le Bourreau",
        "Le Despote",
        "Le Gremlin",
        "L'Indien",
        "Natif",
        "L'Extermin.",
        "Pouchkine",
        "Pied-de-biche",
        "La Bavure",
        "Vendredi",
        "Bagel",
        "Le Fou",
        "Le Chacal",
        "Neptune",
        "Le Marchand",
        "L'Important",
        "Le Rasoir",
        "Buddy",
        "Panadol",
        "Le Veinard",
        "Dolittle",
        "L'Étrangleur",
        "La Tête",
        "Le Pare-chocs",
        "La Gâchette",
        "L'Oeil de lynx",
        "Le Flambeur",
        "Servil",
        "L'Idole",
        "Le Furet",
        "Le Dealer",
        "Le Poudrier",
        "La Crête",
        "Le Barbare",
        "Le Resquilleur",
        "Le Monstre",
        "Le Costaud",
        "Le Cadre",
        "L'Aviateur",
        "Le Curseur",
        "Le Ravioli",
        "Le Glacé",
        "La Dynamite",
        "La Lime",
        "Batiy",
        "Le Tourbillon",
        "Sérieux",
        "Le Pianiste",
        "Capitaine",
        "Le Taureau",
        "Le Bourge",
        "L'Handicapé",
        "Le Chimiste",
        "L'Invétéré",
        "La Cible",
        "Le Morveux",
        "Le Tambourin",
        "Le Silex",
        "Le Rongeur",
        "Commodore",
        "Le Bureaucrate",
        "Icare",
        "Le Voûté",
        "Le Rêveur",
        "Le Moteur",
        "Leshiy",
        "Le Scarabée",
        "Lemming",
        "Le Cobaye",
        "Le Menhir",
        "Le Déserteur",
        "La Croix",
        "Dandy",
        "La Capuche",
        "Le Pif",
        "Duremar",
        "Crâne d'oeuf",
        "Le Ramoneur",
        "Le Cintré",
        "La Plume",
        "Le Sauvage",
        "L'Artiste",
        "Flak",
        "L'Oie",
        "La Mort",
        "Le Ballot",
        "Nelson",
        "Le Radical",
        "Le Mutilé",
        "Le Pétrolier",
        "Le Dauphin",
        "La Quenelle",
        "La Mèche",
        "Le Footeux",
        "L'Affûteur",
        "Le Prince",
        "Nocturne",
        "La Brèche",
        "Le Globe",
        "Le Rémouleur",
        "Le Cosaque",
        "Le Juge",
        "L'Étudiant",
        "Le Bolide",
        "L'Atout",
        "Le Râleur",
        "Fripouille",
        "Karma",
        "Le Parrain",
        "Chebur",
        "Le Troqueur",
        "Le Boucher",
        "Comanche",
        "La Danseuse",
        "Le Vautour",
        "Le Boss",
        "Le Piétiste",
        "Le Cavalier",
        "L'Infirme",
        "L'Épineux",
        "Le Perdant",
        "Le Spaghetti",
        "La Grenade",
        "L'Agent",
        "Gorynich",
        "Tiranas",
        "La Râpe",
        "Le Serpent",
        "Pilote",
        "Cosmos",
        "La Brique",
        "Bulkin",
        "Le Peigne",
        "Néant",
        "La Latte",
        "La Chique",
        "Le Mutileur",
        "La Fraise",
        "Le Globuleux",
        "Pâte à modeler",
        "Le Prophète",
        "Le Coffre",
        "Shtirlits",
        "Le Porteur",
        "Jack",
        "Le Chargeur",
        "Tête brûlée",
        "Le Mousse",
        "Le Poinçon",
        "Déshydraté",
        "L'Estropieur",
        "Le Mécano",
        "Patsyuk",
        "Le Roi",
        "Le Rouge",
        "Le Fier",
        "L'Aveugle",
        "L'Hybride",
        "Le Cercueil",
        "La Tour",
        "L'Élan",
        "Le Coma",
        "Le Taon",
        "La Saucisse",
        "La Machine",
        "Le Tanné",
        "Tas de viande",
        "Aède",
        "Le Tristounet",
        "Le Chauffeur",
        "Le Comique",
        "Sultan",
        "Le Laitier",
        "La Crosse",
        "Le Maçon",
        "Le Babouin",
        "Roquefort",
        "Le Mou",
        "Le Rouillé",
        "Le Mammouth",
        "L'Espiègle",
        "La Blatte",
        "La Pomme",
        "Le Berger",
        "L'Aventurier",
        "Le Dock",
        "La Gangrène",
        "La Tarentule",
        "Le Badaud",
        "Le Parano",
        "Le Toubib",
        "Formidable",
        "L'Isotope",
        "Le Putride",
        "La Serrure",
        "Le Planeur",
        "Le Maure",
        "Le Bosco",
        "L'Accordeur",
        "Charlatan",
        "Le Prêtre",
        "Le Coursier",
        "Le Hippie",
        "Le Vagabond",
        "Le Criquet",
        "Le Héros",
        "Le Canari",
        "Pile",
        "L'Esthète",
        "Le Placard",
        "Le Boeuf",
        "Skiff",
        "Spliff",
        "Le Mont.",
        "Le Pompier",
        "L'Arrache",
        "Le Diplômé",
        "Le Bleu",
        "Le Rancunier",
        "Le Géologue",
        "Le Nerveux",
        "Le Juste",
        "Le Glouton",
        "La Clé",
        "La Citrouille",
        "Le Rockeur",
        "Le Bras droit",
        "Le Clown",
        "Le Croco",
        "Le Parasite",
        "L'Espion",
        "Le Plongeur",
        "Le Cobra",
        "La Loque",
        "Boulon",
        "Kaschey",
        "Le Poing",
        "L'Hélico",
        "Découvreur",
        "Le Clou",
        "La Crapule",
        "L'Électricien",
        "Le Fumeur",
        "L'Accordéon",
        "Ninja",
        "L'Athlète",
        "Chapayev",
        "Le Serrurier",
        "Le Poing ",
        "Le Poivré",
        "Le Visiteur",
        "Le Favori",
        "Le Vandale",
        "Le Facteur",
        "Le Borgne",
        "Le Pirate",
        "Le Belliqueux",
        "Le Rasta",
        "Le Pasteur",
        "Le Penseur",
        "Le Loir",
        "La Bécane",
        "Le Suspect",
        "Le Convoyeur",
        "Le Ranger",
        "Le Prof",
        "Le Grison",
        "Le Natif",
        "Le Rabat-joie",
        "Charbonnier",
        "Leary",
        "Le Grincheux",
        "La Baïonnette",
        "Le Pic",
        "Barmaley",
        "L'Ermite",
        "La Hache",
        "Le Rocher",
        "Kutuzov",
        "Cheburashka",
        "Chingachuk",
        "Le Diplomate",
        "Robin",
        "Le Poilu",
        "Le Zigoto",
        "Le Comptable",
        "Le Bavard",
        "Fusil pompe",
        "Le Dinosaure",
        "Le Microbe",
        "Le Tuyau",
        "Pacifique",
        "Le Messager",
        "Le Moustique",
        "Le Lièvre",
        "Prométhée",
        "L'Épaulette",
        "Le Graphe",
        "Le Minable",
        "Le Lord",
        "Le Collier",
        "Le Poète",
        "Le Touriste",
        "Le Novateur",
        "L'Immortel",
        "Le Modérateur",
        "Bidon",
        "Sheriff",
        "Le Cynique",
        "Kagor",
        "Ryazansky",
        "Le Décadent",
        "Le Cheval",
        "Parachute",
        "Le Boa",
        "La Fourmi",
        "Le Joueur",
        "Le Paysan",
        "Le Chien",
        "Le Voleur",
        "Le Bossu",
        "Zmur",
        "Le Louchard",
        "La Colonne",
        "Le Ridé",
        "Le Secrétaire",
        "Le Bombé",
        "La Dépouille",
        "Le Balafré",
        "Le Pétard",
        "Le Légiste",
        "La Boussole",
        "La Lentille",
        "Le Magnat",
        "Bourbon",
        "Le Banquier",
        "Le Cavaleur",
        "La Mauviette",
        "Flamen",
        "Les Crocs",
        "Le Ver",
        "La Fusée",
        "Le Joker",
        "Le Faucon",
        "Le Gras",
        "La Cloche",
        "La Marmotte",
        "Sac d'os",
        "L'Expert",
        "Le Traînard",
        "Le Sniper",
        "Maigre",
        "La Carpe",
        "Black",
        "Le Chat",
        "Don Juan",
        "Le Patriarche",
        "Le Malin",
        "Nickel",
        "Oscar",
        "Simplet",
        "Le Samouraï",
        "Le Gnome",
        "L'imberbe",
        "Le Spirituel",
        "Cidre",
        "L'Apiculteur",
        "Scoop",
        "Officier d'intervention",
        "L'Outarde",
        "Le Type",
        "Le Réacteur",
        "Maniaque",
        "Oeil de Lynx",
        "Napoléon",
        "Piranha",
        "L'Insecte",
        "Le Tueur",
        "Tamia",
        "L'Ancêtre",
        "Guérisseur",
        "L'Armurier",
        "Teddy",
        "Clodo",
    ],
}
