name: Testing

on: push

jobs:
  pytest:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    strategy:
      matrix:
        py_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.py_version }}"
          cache: "poetry"
      - name: Install deps
        run: poetry install
      - name: Run pytest check
        run: poetry run pytest -vv --cov="faker_stalker_names" .
      - name: Generate report
        run: poetry run coverage xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-latest' && matrix.py_version == '3.9'
